#Perintah untuk menjalankan aplikasi web by CukiD
FROM node:alpine

WORKDIR /usr/src/app
#lokasi kerja docker
COPY package*.json /usr/src/app/
#peng-copyan file dukungan web disini semua filenya hanya berkestendi .json saja
RUN npm install
#install npm
COPY . /usr/src/app/
#meng-copy semua ke lokasi kerja docker
EXPOSE 3000
#konfigurasi port ke 3000
CMD ["node", "app.js"]
#menjalankan aplikasi web
