version: '3'
#versi bisa dicek di web docker compose

services:
    nodnginx-app:
        build:
          context: ./node_app
          #lokasi aplikasi web
        user: root
        container_name: nodenginxserver
        hostname: nodenginxserver
        ports:
            - "3000:3000"
        networks:
            - nodnginx-net
    nginx:
        build:
          context: ./nginx
          #lokasi nginx
        user: root
        container_name: nginx
        hostname: nginx
        depends_on:
            - nodnginx-app
        #depens_on untuk mengecek servis nodnginx-app apabila sudah berjalan
        #maka kanan dijalankan servis nginx
        networks:
            - nodnginx-net

networks:
  nodnginx-net:
